use crate::{
    AnyElement, ElementId, IntoElement, IntoItemMatch, IntoListMatch, IntoMatchValues, ItemMatch,
    ListMatch, SharedString,
    reflection::{ReflectedElement, ReflectedTrait, ReflectedTraits, ReflectionGroup},
};
use smallvec::SmallVec;
use std::{
    cell::{Cell, RefCell},
    marker::PhantomData,
    num::NonZeroUsize,
    rc::Rc,
};

/// The reflection group used by selectors without a reflected trait predicate.
#[doc(hidden)]
pub struct NoReflectedTraits;

impl ReflectionGroup for NoReflectedTraits {}

/// Selects elements relative to an element tree root.
pub struct Select<Group = NoReflectedTraits>
where
    Group: ReflectionGroup,
{
    matcher: SelectorMatcher,
    group: PhantomData<fn() -> Group>,
}

struct SelectorMatcher {
    scope: SelectScope,
    reflected_traits: SmallVec<[ReflectedTrait; 2]>,
    element_id: Option<ItemMatch<ElementId>>,
    classes: SmallVec<[ListMatch<SharedString>; 2]>,
    nth: Option<usize>,
    every: Option<NonZeroUsize>,
}

#[derive(Clone, Copy)]
enum SelectScope {
    This,
    Children,
    Descendants,
}

impl Select<NoReflectedTraits> {
    /// Selects the element on which the selector is installed.
    pub fn this() -> Self {
        Self::new(SelectScope::This)
    }

    /// Selects direct children of the element on which the selector is installed.
    pub fn children() -> Self {
        Self::new(SelectScope::Children)
    }

    /// Selects every descendant of the element on which the selector is installed.
    pub fn descendants() -> Self {
        Self::new(SelectScope::Descendants)
    }

    fn new(scope: SelectScope) -> Self {
        Self {
            matcher: SelectorMatcher {
                scope,
                reflected_traits: SmallVec::new(),
                element_id: None,
                classes: SmallVec::new(),
                nth: None,
                every: None,
            },
            group: PhantomData,
        }
    }

    /// Requires matching elements to reflect every trait in the given trait set.
    pub fn reflects<Traits>(mut self, reflected_traits: Traits) -> Select<Traits::Group>
    where
        Traits: ReflectedTraits,
    {
        self.matcher
            .reflected_traits
            .extend(reflected_traits.reflected_traits());

        Select {
            matcher: self.matcher,
            group: PhantomData,
        }
    }
}

impl<Group> Select<Group>
where
    Group: ReflectionGroup,
{
    /// Matches one element ID, optionally negated with [`crate::not`].
    ///
    /// Composite IDs such as `("row", 3_usize)` remain one ID. A negated ID also
    /// matches elements without an ID. Calling this method again replaces the ID condition.
    ///
    /// ```compile_fail
    /// use gpui::Select;
    ///
    /// let selector = Select::children().id(["save", "cancel"]);
    /// ```
    ///
    /// ```compile_fail
    /// use gpui::{Select, any};
    ///
    /// let selector = Select::children().id(any(["save", "cancel"]));
    /// ```
    pub fn id<Kind>(mut self, element_id: impl IntoItemMatch<ElementId, Kind>) -> Self {
        self.matcher.element_id = Some(element_id.into_item_match());

        self
    }

    /// Matches class membership using values, arrays, vectors, slices, or tuples.
    ///
    /// Collections require every expression to match. Use [`crate::any`] for OR,
    /// and [`crate::not`] to negate an expression. Repeated calls require all conditions.
    ///
    /// ```
    /// use gpui::{Select, any, not};
    ///
    /// let selector = Select::children().class(("apple", "pear", not("plum")));
    /// let selector = Select::children().class(not(any(["apple", "pear"])));
    /// ```
    pub fn class<Kind>(mut self, class: impl IntoListMatch<SharedString, Kind>) -> Self {
        self.matcher.classes.push(class.into_list_match());

        self
    }

    /// Selects the matching element at a zero-based index in layout visitation order.
    ///
    /// Scope, reflected traits, classes, and ID conditions run before indexing,
    /// regardless of builder order. Late-created children continue the same index sequence
    /// in execution order, including deferred prepaint priority. Nodes generated by this
    /// rule are excluded, and eligible matching nodes advance the sequence once.
    /// Temporary measurement elements are excluded, and virtualized lists only index
    /// materialized elements. Calling this method again replaces the index condition.
    pub fn nth(mut self, idx: usize) -> Self {
        self.matcher.nth = Some(idx);

        self
    }

    /// Selects matching indexes `0, step, 2 * step, ...` in layout visitation order.
    ///
    /// Uses the same indexing rules as [`Self::nth`]. If both methods are used,
    /// both conditions test the same index. Calling this method again replaces the interval.
    ///
    /// # Panics
    ///
    /// Panics if `step` is zero.
    pub fn every(mut self, step: usize) -> Self {
        self.matcher.every =
            Some(NonZeroUsize::new(step).expect("selector interval must be nonzero"));

        self
    }

    fn into_matcher(self) -> SelectorMatcher {
        self.matcher
    }
}

impl SelectorMatcher {
    fn matches_predicates(&self, element: &AnyElement) -> bool {
        if !self
            .reflected_traits
            .iter()
            .all(|reflected_trait| element.implements_trait(*reflected_trait))
        {
            return false;
        }

        if let Some(element_id) = self.element_id.as_ref()
            && !element_id.evaluate(&|expected| element.element_id().as_ref() == Some(expected))
        {
            return false;
        }

        if !self
            .classes
            .iter()
            .all(|class| class.matches(element.classes()))
        {
            return false;
        }

        true
    }

    fn has_position(&self) -> bool {
        self.nth.is_some() || self.every.is_some()
    }

    fn includes_position(&self, idx: usize) -> bool {
        self.nth.is_none_or(|expected| idx == expected)
            && self.every.is_none_or(|step| idx.is_multiple_of(step.get()))
    }

    fn includes_depth(&self, depth: usize) -> bool {
        match self.scope {
            SelectScope::This => depth == 0,
            SelectScope::Children => depth == 1,
            SelectScope::Descendants => depth >= 1,
        }
    }
}

/// Adds selector metadata and transformations to elements.
pub trait SelectableElement: IntoElement + Sized {
    /// Tags this element with one class or a collection of positive class names.
    ///
    /// Arrays, vectors, slices, and tuples are supported. Boolean expressions are
    /// only accepted by [`Select::class`].
    ///
    /// ```compile_fail
    /// use gpui::{SelectableElement, div, not};
    ///
    /// let element = div().class(not("apple"));
    /// ```
    fn class<Kind>(self, class: impl IntoMatchValues<SharedString, Kind>) -> AnyElement {
        let mut element = self.into_any_element();
        class.extend_match_values(element.classes_mut());

        element
    }

    /// Transforms each element matched by the selector before it requests layout.
    ///
    /// A rule evaluates a node once at its first eligible layout visit in an attempt,
    /// including failed predicates. Recomputing an existing layout never applies transforms
    /// again. The callback may mutate, wrap, discard, or replace its input.
    ///
    /// Elements first erased during the callback, and descendants they later create,
    /// are excluded from that rule. Other rules can still select them. Moving an existing
    /// erased element preserves its visits and generation ancestry, so untouched original
    /// descendants inside a new wrapper remain eligible.
    ///
    /// ```
    /// use gpui::{ParentElement, Select, SelectableElement, div};
    ///
    /// div().child(div().class("icon")).select(
    ///     Select::descendants().class("icon"),
    ///     |element| div().child(element),
    /// );
    /// ```
    fn select<Group, Output>(
        self,
        selector: Select<Group>,
        mut transform: impl FnMut(ReflectedElement<Group>) -> Output + 'static,
    ) -> AnyElement
    where
        Group: ReflectionGroup,
        Output: IntoElement + 'static,
    {
        let mut element = self.into_any_element();
        let transform = move |element| transform(ReflectedElement::new(element)).into_any_element();
        element.add_selector(PendingSelector::new(
            selector.into_matcher(),
            Box::new(transform),
        ));

        element
    }
}

impl<ElementType> SelectableElement for ElementType where ElementType: IntoElement {}

pub(crate) struct ElementMetadata {
    pub(crate) classes: SmallVec<[SharedString; 2]>,
    pub(crate) selectors: Vec<PendingSelector>,
    pub(crate) node_state: Option<SelectorNodeState>,
}

impl ElementMetadata {
    pub(crate) fn new() -> Self {
        Self {
            classes: SmallVec::new(),
            selectors: Vec::new(),
            node_state: None,
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) struct SelectorRuleId(u64);

#[derive(Clone, Copy, Default, PartialEq, Eq)]
struct LayoutAttemptId(u64);

struct SelectorVisit {
    rule: SelectorRuleId,
    attempt: LayoutAttemptId,
}

#[derive(Default)]
pub(crate) struct SelectorNodeState {
    visited: SmallVec<[SelectorVisit; 2]>,
    pub(crate) generated_by: SmallVec<[SelectorRuleId; 2]>,
}

impl SelectorNodeState {
    pub(crate) fn generated(generated_by: SmallVec<[SelectorRuleId; 2]>) -> Self {
        Self {
            generated_by,
            ..Self::default()
        }
    }

    fn record_visit(&mut self, rule: SelectorRuleId, attempt: LayoutAttemptId) -> bool {
        self.visited.retain(|visit| visit.attempt == attempt);

        if self.visited.iter().any(|visit| visit.rule == rule) {
            return false;
        }

        self.visited.push(SelectorVisit { rule, attempt });

        true
    }
}

type SelectorTransform = Box<dyn FnMut(AnyElement) -> AnyElement>;

#[derive(Clone)]
pub(crate) struct PendingSelector(Rc<SelectorRule>);

impl PendingSelector {
    fn new(matcher: SelectorMatcher, transform: SelectorTransform) -> Self {
        let identity = NEXT_SELECTOR_RULE_ID.with(|next| {
            let identity = next.get();
            next.set(
                identity
                    .checked_add(1)
                    .expect("selector rule IDs exhausted"),
            );

            SelectorRuleId(identity)
        });

        Self(Rc::new(SelectorRule {
            identity,
            matcher,
            transform: RefCell::new(Some(transform)),
            next_match_idx: Cell::new(0),
        }))
    }

    pub(crate) fn identity(&self) -> SelectorRuleId {
        self.0.identity
    }
}

struct SelectorRule {
    identity: SelectorRuleId,
    matcher: SelectorMatcher,
    transform: RefCell<Option<SelectorTransform>>,
    next_match_idx: Cell<usize>,
}

struct SelectorCallbackLease<'rule> {
    rule: &'rule SelectorRule,
    transform: Option<SelectorTransform>,
}

impl SelectorRule {
    fn try_lease(&self) -> Option<SelectorCallbackLease<'_>> {
        let transform = self.transform.borrow_mut().take()?;

        Some(SelectorCallbackLease {
            rule: self,
            transform: Some(transform),
        })
    }
}

impl Drop for SelectorCallbackLease<'_> {
    fn drop(&mut self) {
        let transform = self
            .transform
            .take()
            .expect("selector callback lease is empty");
        self.rule.transform.borrow_mut().replace(transform);
    }
}

#[derive(Clone)]
struct SelectorBinding {
    rule: Rc<SelectorRule>,
    depth: usize,
}

#[derive(Clone, Default)]
pub(crate) struct SelectorContext {
    bindings: SmallVec<[SelectorBinding; 4]>,
    measurement_depth: usize,
    attempt: LayoutAttemptId,
    generated_by: SmallVec<[SelectorRuleId; 2]>,
}

thread_local! {
    static SELECTOR_CONTEXT: RefCell<SelectorContext> = RefCell::new(SelectorContext::default());
    static NEXT_SELECTOR_RULE_ID: Cell<u64> = const { Cell::new(1) };
    static NEXT_LAYOUT_ATTEMPT_ID: Cell<u64> = const { Cell::new(1) };
}

pub(crate) fn has_active_selectors() -> bool {
    SELECTOR_CONTEXT.with_borrow(|context| !context.bindings.is_empty())
}

pub(crate) fn capture_selector_context() -> SelectorContext {
    SELECTOR_CONTEXT.with_borrow(Clone::clone)
}

pub(crate) struct SelectorContextGuard {
    previous: SelectorContext,
}

impl SelectorContextGuard {
    fn enter(context: SelectorContext) -> Self {
        let previous = SELECTOR_CONTEXT.replace(context);

        Self { previous }
    }
}

impl Drop for SelectorContextGuard {
    fn drop(&mut self) {
        SELECTOR_CONTEXT.replace(std::mem::take(&mut self.previous));
    }
}

pub(crate) fn begin_selector_layout_attempt() -> SelectorContextGuard {
    let attempt = NEXT_LAYOUT_ATTEMPT_ID.with(|next| {
        let attempt = next.get();
        next.set(
            attempt
                .checked_add(1)
                .expect("layout attempt IDs exhausted"),
        );

        LayoutAttemptId(attempt)
    });

    SelectorContextGuard::enter(SelectorContext {
        attempt,
        ..SelectorContext::default()
    })
}

pub(crate) fn with_selector_context<ResultType>(
    context: SelectorContext,
    operation: impl FnOnce() -> ResultType,
) -> ResultType {
    let context_guard = SelectorContextGuard::enter(context);
    let result = operation();
    drop(context_guard);

    result
}

pub(crate) fn generation_ancestry() -> SmallVec<[SelectorRuleId; 2]> {
    SELECTOR_CONTEXT.with_borrow(|context| context.generated_by.clone())
}

pub(crate) fn with_generation_ancestry<ResultType>(
    generated_by: SmallVec<[SelectorRuleId; 2]>,
    operation: impl FnOnce() -> ResultType,
) -> ResultType {
    let mut context = capture_selector_context();
    context.generated_by = generated_by;

    with_selector_context(context, operation)
}

fn activate_attached_selectors(selectors: &[PendingSelector]) {
    SELECTOR_CONTEXT.with_borrow_mut(|context| {
        for selector in selectors {
            if context
                .bindings
                .iter()
                .any(|binding| binding.rule.identity == selector.identity())
            {
                continue;
            }

            context.bindings.push(SelectorBinding {
                rule: selector.0.clone(),
                depth: 0,
            });
        }
    });
}

pub(crate) fn with_attached_selectors<ResultType>(
    selectors: &[PendingSelector],
    operation: impl FnOnce() -> ResultType,
) -> ResultType {
    with_selector_context(capture_selector_context(), || {
        activate_attached_selectors(selectors);

        operation()
    })
}

pub(crate) fn with_selector_measurement<ResultType>(
    operation: impl FnOnce() -> ResultType,
) -> ResultType {
    let mut context = capture_selector_context();
    context.measurement_depth += 1;

    with_selector_context(context, operation)
}

pub(crate) fn with_selector_transaction<Success, Failure>(
    operation: impl FnOnce() -> Result<Success, Failure>,
) -> Result<Success, Failure> {
    let checkpoint = SELECTOR_CONTEXT.with_borrow(|context| {
        context
            .bindings
            .iter()
            .filter(|binding| binding.rule.matcher.has_position())
            .map(|binding| (binding.rule.clone(), binding.rule.next_match_idx.get()))
            .collect::<SmallVec<[_; 4]>>()
    });
    let result = operation();

    if result.is_err() {
        for (rule, idx) in checkpoint {
            rule.next_match_idx.set(idx);
        }
    }

    result
}

pub(crate) fn with_deeper_selector_depth<ResultType>(
    operation: impl FnOnce() -> ResultType,
) -> ResultType {
    let mut context = capture_selector_context();

    for binding in &mut context.bindings {
        binding.depth += 1;
    }

    with_selector_context(context, operation)
}

pub(crate) fn apply_active_selectors(element: &mut AnyElement) {
    let mut selector_idx = 0;

    loop {
        let Some((binding, measuring, attempt)) = SELECTOR_CONTEXT.with_borrow(|context| {
            context
                .bindings
                .get(selector_idx)
                .cloned()
                .map(|binding| (binding, context.measurement_depth > 0, context.attempt))
        }) else {
            break;
        };

        selector_idx += 1;
        let rule = binding.rule;

        if !rule.matcher.includes_depth(binding.depth)
            || (measuring && rule.matcher.has_position())
            || element
                .selector_generation_ancestry()
                .contains(&rule.identity)
            || rule.transform.borrow().is_none()
        {
            continue;
        }

        if !element
            .selector_node_state_mut()
            .record_visit(rule.identity, attempt)
            || !rule.matcher.matches_predicates(element)
        {
            continue;
        }

        if rule.matcher.has_position() {
            let idx = rule.next_match_idx.get();
            rule.next_match_idx.set(idx + 1);

            if !rule.matcher.includes_position(idx) {
                continue;
            }
        }

        let Some(mut callback) = rule.try_lease() else {
            continue;
        };

        let attached = element.attached_selectors();
        let selected = element.take();
        let mut ancestry = selected.selector_generation_ancestry();
        ancestry.push(rule.identity);

        let replacement = with_generation_ancestry(ancestry, || {
            callback
                .transform
                .as_mut()
                .expect("selector callback lease is empty")(selected)
        });

        assert!(
            replacement.is_before_layout(),
            "selector replacement must not have requested layout"
        );

        element.replace(replacement);
        element.inherit_attached_selectors(attached);
        activate_attached_selectors(&element.attached_selectors());
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        AnyWindowHandle, App, AppContext, AvailableSpace, Context, Element, Empty,
        InteractiveElement, ListAlignment, ListState, ParentElement, Pixels, Render, Size,
        StyleRefinement, Styled, TestAppContext, VisualTestContext, Window, any, div, list, not,
        px, rgb, size, uniform_list,
    };
    use std::{cell::Cell, panic, rc::Rc};

    struct SelectorTestView {
        render: Box<dyn Fn() -> AnyElement>,
    }

    impl Render for SelectorTestView {
        #[allow(unused_variables)]
        fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
            (self.render)()
        }
    }

    fn draw_selector_window(window: AnyWindowHandle, cx: &mut TestAppContext) {
        cx.update_window(window, |_view, window, cx| {
            window.draw(cx).clear(cx);
        })
        .unwrap();
    }

    fn record_match(matches: &Rc<RefCell<Vec<ElementId>>>, element: &AnyElement) {
        let mut matches = matches.borrow_mut();
        assert!(matches.len() < 16, "selector rewrite did not terminate");
        matches.push(element.element_id().unwrap());
    }

    fn draw_selector_tree(
        cx: &mut TestAppContext,
        build: impl FnOnce() -> AnyElement,
    ) -> &mut VisualTestContext {
        let visual = cx.add_empty_window();
        visual.draw(
            Default::default(),
            size(px(100.), px(100.)),
            |_window, _cx| build(),
        );

        visual
    }

    #[track_caller]
    fn assert_matches(matches: &Rc<RefCell<Vec<ElementId>>>, expected: &[&'static str]) {
        let expected = expected
            .iter()
            .map(|label| ElementId::from(*label))
            .collect::<Vec<_>>();
        assert_eq!(*matches.borrow(), expected);
    }

    #[crate::test]
    fn wrapping_preserves_identity_metadata_and_original_descendants(cx: &mut TestAppContext) {
        let wrapped = Rc::new(RefCell::new(Vec::new()));
        let wrapper_children = Rc::new(RefCell::new(Vec::new()));
        let styled = Rc::new(RefCell::new(Vec::new()));

        let matched = wrapped.clone();
        let children = wrapper_children.clone();
        let renamed = styled.clone();
        let attached = styled.clone();

        let visual = draw_selector_tree(cx, move || {
            div()
                .child(
                    div()
                        .id("outer")
                        .debug_selector(|| "outer".into())
                        .child(
                            div()
                                .id("inner")
                                .debug_selector(|| "inner".into())
                                .class(["icon", "leaf"]),
                        )
                        .class("icon")
                        .select(
                            Select::descendants().class("leaf").reflects(crate::Styled),
                            move |element| {
                                record_match(&attached, &element.element);

                                element.size(px(12.))
                            },
                        ),
                )
                .select(
                    Select::descendants()
                        .id("outer")
                        .reflects(crate::InteractiveElement),
                    |element| element.id("renamed"),
                )
                .select(
                    Select::descendants()
                        .id("renamed")
                        .class("icon")
                        .reflects(crate::Styled),
                    move |element| {
                        record_match(&renamed, &element.element);

                        element.size(px(48.))
                    },
                )
                .select(Select::descendants().class("icon"), move |element| {
                    record_match(&matched, &element.element);
                    let children = children.clone();

                    div()
                        .child(element)
                        .select(Select::children(), move |element| {
                            record_match(&children, &element.element);

                            element
                        })
                })
        });

        assert_matches(&wrapped, &["renamed", "inner"]);
        assert_eq!(*wrapper_children.borrow(), *wrapped.borrow());
        assert_matches(&styled, &["renamed", "inner"]);
        assert_eq!(
            visual.debug_bounds("outer").unwrap().size,
            size(px(48.), px(48.))
        );
        assert_eq!(
            visual.debug_bounds("inner").unwrap().size,
            size(px(12.), px(12.))
        );
    }

    #[crate::test]
    fn generation_exclusions_survive_mutation_replacement_and_rule_chains(cx: &mut TestAppContext) {
        let generating = Rc::new(RefCell::new(Vec::new()));
        let later = Rc::new(RefCell::new(Vec::new()));
        let installed = Rc::new(RefCell::new(Vec::new()));

        let first = generating.clone();
        let second = later.clone();
        let new_rules = installed.clone();

        draw_selector_tree(cx, move || {
            let mut prebuilt = Some(div().id("prebuilt").class("icon"));
            let mut concrete = Some(div().id("captured-concrete"));

            div()
                .child(div().id("mutated").class("icon"))
                .child(div().id("replaced").class("icon"))
                .select(
                    Select::descendants()
                        .class("icon")
                        .reflects(crate::ParentElement),
                    move |element| {
                        record_match(&first, &element.element);

                        if element.element.element_id() == Some(ElementId::from("replaced")) {
                            return div()
                                .id("from-first")
                                .child(div().id("fresh-child").class("icon"))
                                .class("icon");
                        }

                        if element.element.element_id() == Some(ElementId::from("mutated")) {
                            return element
                                .child(div().id("appended").class("icon"))
                                .child(prebuilt.take().unwrap())
                                .child(concrete.take().unwrap().class("icon"))
                                .into_any_element();
                        }

                        element.into_any_element()
                    },
                )
                .select(Select::descendants().class("icon"), move |element| {
                    record_match(&second, &element.element);

                    if element.element.element_id() != Some(ElementId::from("from-first")) {
                        return element.into_any_element();
                    }

                    let this = new_rules.clone();
                    let children = new_rules.clone();

                    div()
                        .id("from-second")
                        .child(element)
                        .child(div().id("generated-child").class("icon"))
                        .class("icon")
                        .select(Select::this().reflects(crate::Styled), move |element| {
                            record_match(&this, &element.element);

                            element.size(px(40.))
                        })
                        .select(Select::children().reflects(crate::Styled), move |element| {
                            record_match(&children, &element.element);

                            element.size(px(8.))
                        })
                })
        });

        assert_matches(&generating, &["mutated", "prebuilt", "replaced"]);
        assert_matches(
            &later,
            &[
                "mutated",
                "appended",
                "prebuilt",
                "captured-concrete",
                "from-first",
                "fresh-child",
            ],
        );
        assert_matches(
            &installed,
            &["from-second", "from-first", "generated-child"],
        );
    }

    #[crate::test]
    fn generated_factories_preserve_origins_and_original_deferred_subtrees(
        cx: &mut TestAppContext,
    ) {
        let generating = Rc::new(RefCell::new(Vec::new()));
        let later = Rc::new(RefCell::new(Vec::new()));

        let generating_for_render = generating.clone();
        let later_for_render = later.clone();
        let window = cx.add_window(move |_window, _cx| SelectorTestView {
            render: Box::new(move || {
                let matches = generating_for_render.clone();
                let concrete = generating_for_render.clone();
                let later = later_for_render.clone();

                div()
                    .size_full()
                    .child(
                        div()
                            .id("original")
                            .child(div().id("original-child").class("icon"))
                            .child(crate::container_query(|_size, _window, _cx| {
                                div().id("original-late").class("icon")
                            }))
                            .class("icon"),
                    )
                    .child(crate::deferred(crate::container_query(
                        |_size, _window, _cx| div().id("ordinary-late").class("icon"),
                    )))
                    .child(div().id("concrete-original").class("factory"))
                    .select(Select::descendants().class("icon"), move |element| {
                        record_match(&matches, &element.element);

                        if element.element.element_id() != Some(ElementId::from("original")) {
                            return element.into_any_element();
                        }

                        crate::deferred(crate::container_query(move |_size, _window, _cx| {
                            div()
                                .id("generated-late")
                                .child(element)
                                .child(crate::deferred(crate::container_query(
                                    |_size, _window, _cx| {
                                        div().id("nested-generated").class("icon")
                                    },
                                )))
                                .class("icon")
                        }))
                        .into_any_element()
                    })
                    .select(Select::descendants().class("factory"), move |element| {
                        record_match(&concrete, &element.element);

                        crate::container_query(|_size, _window, _cx| {
                            div().id("concrete-generated").class("factory")
                        })
                    })
                    .select(
                        Select::descendants()
                            .class(any(["icon", "factory"]))
                            .reflects(crate::Styled),
                        move |element| {
                            record_match(&later, &element.element);

                            element.size(px(16.))
                        },
                    )
            }),
        });

        generating.borrow_mut().clear();
        later.borrow_mut().clear();
        draw_selector_window(window.into(), cx);

        assert_matches(
            &generating,
            &[
                "original",
                "concrete-original",
                "original-child",
                "original-late",
                "ordinary-late",
            ],
        );
        assert_matches(
            &later,
            &[
                "concrete-generated",
                "generated-late",
                "original",
                "original-child",
                "original-late",
                "ordinary-late",
                "nested-generated",
            ],
        );
    }

    #[crate::test]
    fn positions_ignore_generated_nodes_and_repeated_or_abandoned_layout(cx: &mut TestAppContext) {
        for select_nth in [false, true] {
            let failed = Rc::new(Cell::new(0));
            let indexed = Rc::new(RefCell::new(Vec::new()));

            let failed_count = failed.clone();
            let matched = indexed.clone();

            let selector = Select::descendants().class("row");
            let selector = if select_nth {
                selector.nth(1)
            } else {
                selector.every(2)
            };

            let retained_size = if select_nth { px(5.) } else { px(20.) };

            draw_selector_tree(cx, move || {
                div()
                    .child(crate::container_query(move |_size, window, cx| {
                        let mut retained = div().id(("row", 0_usize)).size(px(5.)).class("row");
                        let available = AvailableSpace::min_size();
                        let expected_size = size(retained_size, retained_size);
                        let result = window.transact(|window| {
                            assert_eq!(
                                retained.layout_as_root(available, window, cx),
                                expected_size
                            );

                            Err::<(), ()>(())
                        });

                        assert!(result.is_err());
                        for available in [
                            available,
                            size(
                                AvailableSpace::Definite(px(50.)),
                                AvailableSpace::MinContent,
                            ),
                        ] {
                            assert_eq!(
                                retained.layout_as_root(available, window, cx),
                                expected_size
                            );
                        }

                        // A new attempt cannot make a requested drawable transform again.
                        with_selector_context(
                            SelectorContext {
                                attempt: LayoutAttemptId(u64::MAX),
                                ..capture_selector_context()
                            },
                            || {
                                assert_eq!(
                                    retained.layout_as_root(available, window, cx),
                                    expected_size
                                );
                            },
                        );

                        div().children((1_usize..5).map(|idx| div().id(("row", idx)).class("row")))
                    }))
                    .select(Select::descendants().class("renamed"), move |element| {
                        failed_count.set(failed_count.get() + 1);

                        element
                    })
                    .select(selector, move |element| {
                        record_match(&matched, &element.element);

                        div()
                            .size(px(20.))
                            .child(element.class("renamed"))
                            .class("row")
                    })
            });

            let expected = if select_nth {
                vec![2_usize]
            } else {
                vec![0_usize, 1, 3]
            };

            let expected = expected
                .into_iter()
                .map(|idx| ElementId::from(("row", idx)))
                .collect::<Vec<_>>();
            assert_eq!(failed.get(), 0);
            assert_eq!(*indexed.borrow(), expected);
        }
    }

    #[crate::test]
    fn caught_transform_panics_restore_callbacks_and_construction_context(cx: &mut TestAppContext) {
        let selected = Rc::new(RefCell::new(Vec::new()));
        let observed = selected.clone();
        let recovered = selected.clone();

        draw_selector_tree(cx, move || {
            div()
                .child(crate::container_query(move |_size, window, cx| {
                    let result = panic::catch_unwind(panic::AssertUnwindSafe(|| {
                        window.with_layout_measurement(|window| {
                            let mut doomed = div().id("panic").class("row");
                            doomed.layout_as_root(AvailableSpace::min_size(), window, cx);
                        });
                    }));
                    assert!(result.is_err());

                    div().id("surviving").class("row")
                }))
                .select(Select::descendants().class("row"), move |element| {
                    if element.element.element_id() == Some(ElementId::from("panic")) {
                        let _generated = div().class("row");
                        panic!("transform failed");
                    }

                    record_match(&recovered, &element.element);

                    element
                })
                .select(Select::descendants().class("row").nth(0), move |element| {
                    record_match(&observed, &element.element);

                    element
                })
        });

        assert_matches(&selected, &["surviving", "surviving"]);
        assert!(!has_active_selectors());
        assert!(generation_ancestry().is_empty());

        draw_selector_tree(cx, || {
            div()
                .child(div().class("row"))
                .select(Select::descendants().class("row"), |element| element)
        });
    }

    #[crate::test]
    #[allow(unused_variables)]
    fn combines_class_conditions_with_scalar_ids(cx: &mut TestAppContext) {
        let selected = Rc::new(RefCell::new(Vec::new()));
        let selected_for_render = selected.clone();
        let window = cx.add_window(move |window, cx| SelectorTestView {
            render: Box::new(move || {
                let selected = selected_for_render.clone();

                div()
                    .child(div().id(("row", 0_usize)).class(["apple", "pear"]))
                    .child(div().id(("row", 1_usize)).class(("apple", "pear", "plum")))
                    .child(div().id(("row", 2_usize)).class(vec!["apple", "pear"]))
                    .child(div().id(("row", 3_usize)).class(&["pear"]))
                    .child(div().class("apple"))
                    .select(
                        Select::children()
                            .reflects(crate::Styled)
                            .class((any(["apple", "orange"]), not("plum")))
                            .class("pear")
                            .id(not(("row", 0_usize))),
                        move |element| {
                            selected.borrow_mut().push(element.element.element_id());

                            element.bg(rgb(0x112233))
                        },
                    )
            }),
        });

        selected.borrow_mut().clear();
        draw_selector_window(window.into(), cx);

        assert_eq!(
            *selected.borrow(),
            vec![Some(ElementId::from(("row", 2_usize)))]
        );
    }

    #[crate::test]
    #[allow(unused_variables)]
    fn indexes_filtered_elements_across_layout_and_prepaint(cx: &mut TestAppContext) {
        let selected = Rc::new(RefCell::new(Vec::new()));
        let selected_for_render = selected.clone();
        let window = cx.add_window(move |window, cx| SelectorTestView {
            render: Box::new(move || {
                let selectors = [
                    ("nth", Select::descendants().class("row").nth(2)),
                    ("reordered", Select::descendants().nth(2).class("row")),
                    ("every", Select::descendants().class("row").every(2)),
                    ("both", Select::descendants().class("row").nth(2).every(2)),
                    (
                        "disjoint",
                        Select::descendants().class("row").nth(1).every(2),
                    ),
                    ("missing", Select::descendants().class("row").nth(99)),
                ];
                let mut root = div()
                    .child(div().id("first").class("row"))
                    .child(div().id("unrelated"))
                    .child(div().id("second").class("row"))
                    .child(crate::container_query(|size, window, cx| {
                        div()
                            .id("late")
                            .child(div().id("late-child").class("row"))
                            .class("row")
                    }))
                    .into_any_element();

                for (label, selector) in selectors {
                    let selected = selected_for_render.clone();
                    root = root.select(selector, move |element| {
                        selected
                            .borrow_mut()
                            .push((label, element.element.element_id().unwrap()));

                        element
                    });
                }

                root
            }),
        });
        let expected = vec![
            ("every", ElementId::from("first")),
            ("nth", ElementId::from("late")),
            ("reordered", ElementId::from("late")),
            ("every", ElementId::from("late")),
            ("both", ElementId::from("late")),
        ];

        for redraw in 0..2 {
            selected.borrow_mut().clear();
            draw_selector_window(window.into(), cx);

            assert_eq!(*selected.borrow(), expected);
        }
    }

    #[crate::test]
    #[allow(unused_variables)]
    fn positional_selectors_exclude_list_measurements(cx: &mut TestAppContext) {
        let selected = Rc::new(RefCell::new(Vec::new()));
        let first = Rc::new(RefCell::new(Vec::new()));
        let selected_for_render = selected.clone();
        let first_for_render = first.clone();
        let state = ListState::new(8, ListAlignment::Top, px(0.)).measure_all();
        let window = cx.add_window(move |window, cx| SelectorTestView {
            render: Box::new(move || {
                let selected = selected_for_render.clone();
                let first = first_for_render.clone();

                div()
                    .flex()
                    .flex_col()
                    .w(px(80.))
                    .h(px(120.))
                    .child(
                        uniform_list("uniform", 8, |range, window, cx| {
                            range
                                .map(|idx| {
                                    div()
                                        .id(("uniform-row", idx))
                                        .h(px(20.))
                                        .class("row")
                                        .into_any_element()
                                })
                                .collect()
                        })
                        .h(px(60.))
                        .w_full(),
                    )
                    .child(
                        list(state.clone(), |idx, window, cx| {
                            div().id(("list-row", idx)).h(px(20.)).class("row")
                        })
                        .h(px(60.))
                        .w_full(),
                    )
                    .select(
                        Select::descendants().class("row").every(1),
                        move |element| {
                            selected
                                .borrow_mut()
                                .push(element.element.element_id().unwrap());

                            element
                        },
                    )
                    .select(Select::descendants().class("row").nth(0), move |element| {
                        first
                            .borrow_mut()
                            .push(element.element.element_id().unwrap());

                        element
                    })
            }),
        });
        let expected = ["uniform-row", "list-row"]
            .into_iter()
            .flat_map(|label| (0_usize..3).map(move |idx| ElementId::from((label, idx))))
            .collect::<Vec<_>>();

        for redraw in 0..2 {
            selected.borrow_mut().clear();
            first.borrow_mut().clear();
            draw_selector_window(window.into(), cx);

            assert_eq!(*selected.borrow(), expected);
            assert_eq!(
                *first.borrow(),
                vec![ElementId::from(("uniform-row", 0_usize))]
            );
        }
    }

    #[crate::test]
    fn measurement_helpers_preserve_selector_state(cx: &mut TestAppContext) {
        let available_space = size(AvailableSpace::MaxContent, AvailableSpace::MinContent);
        let expected_size = size(px(48.), px(24.));

        let measure_nested_row = move |window: &mut Window, cx: &mut App| {
            let mut element = div().id("nested-measurement").size(px(8.)).class("row");

            element.layout_as_root(available_space, window, cx)
        };

        let build_measured_row = move |window: &mut Window, cx: &mut App| {
            let nested_size =
                window.with_layout_measurement(|window| measure_nested_row(window, cx));
            let mut element = div().id("during-construction").size(px(8.)).class("row");
            let constructed_size = element.layout_as_root(available_space, window, cx);

            assert_eq!([nested_size, constructed_size], [expected_size; 2]);

            div().id("measured-root").size(px(8.)).class("row")
        };

        let build_panicking_row = |_window: &mut Window, _cx: &mut App| -> Empty {
            panic!("measurement construction failed");
        };

        let render_rows = move |_bounds: Size<Pixels>, window: &mut Window, cx: &mut App| {
            let result = panic::catch_unwind(panic::AssertUnwindSafe(|| {
                window.measure_element(available_space, cx, build_panicking_row);
            }));

            assert!(result.is_err());

            let measured_size = window.measure_element(available_space, cx, build_measured_row);

            assert_eq!(measured_size, expected_size);

            div()
                .child(div().id("first").class("row"))
                .child(div().id("unrelated"))
                .child(div().id("second").class("row"))
        };

        let selected = Rc::new(RefCell::new(Vec::new()));
        let first = selected.clone();
        let every = selected.clone();

        cx.add_empty_window().draw(
            Default::default(),
            size(px(80.), px(120.)),
            move |_window, _cx| {
                div()
                    .child(crate::container_query(render_rows))
                    .select(
                        Select::descendants().class("row").reflects(crate::Styled),
                        |element| element.w(px(48.)).h(px(24.)),
                    )
                    .select(
                        Select::descendants()
                            .class("row")
                            .reflects(crate::Styled)
                            .nth(0),
                        move |element| {
                            first
                                .borrow_mut()
                                .push(("nth", element.element.element_id().unwrap()));

                            element.h(px(99.))
                        },
                    )
                    .select(
                        Select::descendants().class("row").every(2),
                        move |element| {
                            every
                                .borrow_mut()
                                .push(("every", element.element.element_id().unwrap()));

                            element
                        },
                    )
            },
        );

        assert_eq!(
            *selected.borrow(),
            vec![
                ("nth", ElementId::from("first")),
                ("every", ElementId::from("first")),
            ]
        );
    }

    struct CachedSelectorChild {
        renders: Rc<Cell<usize>>,
    }

    impl Render for CachedSelectorChild {
        #[allow(unused_variables)]
        fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
            self.renders.set(self.renders.get() + 1);

            div()
                .id("cached-row")
                .size_full()
                .debug_selector(|| "cached-row".into())
                .class("row")
        }
    }

    #[crate::test]
    #[allow(unused_variables)]
    fn selectors_visit_cached_view_contents_on_each_frame(cx: &mut TestAppContext) {
        let renders = Rc::new(Cell::new(0));
        let renders_for_child = renders.clone();
        let child = cx.new(move |cx| CachedSelectorChild {
            renders: renders_for_child,
        });
        let selected = Rc::new(Cell::new(0));
        let selected_for_render = selected.clone();
        let window = cx.add_window(move |window, cx| SelectorTestView {
            render: Box::new(move || {
                let selected = selected_for_render.clone();
                let mut style = StyleRefinement::default();
                style.size.width = Some(px(40.).into());
                style.size.height = Some(px(20.).into());

                div().child(child.clone().cached(style)).select(
                    Select::descendants().class("row").nth(0),
                    move |element| {
                        selected.set(selected.get() + 1);

                        element
                    },
                )
            }),
        });

        renders.set(0);
        selected.set(0);

        for redraw in 0..2 {
            draw_selector_window(window.into(), cx);

            let bounds = cx
                .update_window(window.into(), |view, window, cx| {
                    window.rendered_frame.debug_bounds["cached-row"]
                })
                .unwrap();

            assert_eq!(bounds.size.width, px(40.));
            assert_eq!(bounds.size.height, px(20.));
        }

        assert_eq!(renders.get(), 2);
        assert_eq!(selected.get(), 2);
    }

    #[test]
    #[should_panic(expected = "selector interval must be nonzero")]
    fn rejects_zero_intervals() {
        Select::children().every(0);
    }

    #[crate::test]
    #[allow(unused_variables)]
    fn restores_positions_when_prepaint_retries(cx: &mut TestAppContext) {
        let selected = Rc::new(RefCell::new(Vec::new()));
        let selected_for_render = selected.clone();
        let window = cx.add_window(move |window, cx| SelectorTestView {
            render: Box::new(move || {
                let selected = selected_for_render.clone();

                div()
                    .child(crate::container_query(|size, window, cx| {
                        let result = window.transact(|window| {
                            let mut discarded = div().id("discarded").class("row");
                            discarded.layout_as_root(
                                size.map(AvailableSpace::Definite),
                                window,
                                cx,
                            );

                            Err::<(), ()>(())
                        });

                        assert!(result.is_err());

                        div().id("committed").class("row")
                    }))
                    .select(Select::descendants().class("row").nth(0), move |element| {
                        selected
                            .borrow_mut()
                            .push(element.element.element_id().unwrap());

                        element
                    })
            }),
        });

        selected.borrow_mut().clear();
        draw_selector_window(window.into(), cx);

        assert_eq!(
            *selected.borrow(),
            vec![ElementId::from("discarded"), ElementId::from("committed")]
        );
    }

    struct SelectorView {
        this_count: Rc<Cell<usize>>,
        children_count: Rc<Cell<usize>>,
        descendants_count: Rc<Cell<usize>>,
        filtered_count: Rc<Cell<usize>>,
    }

    impl Render for SelectorView {
        #[allow(unused_variables)]
        fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
            let this_count = self.this_count.clone();
            let children_count = self.children_count.clone();
            let descendants_count = self.descendants_count.clone();
            let filtered_count = self.filtered_count.clone();

            div()
                .child(div().id("target").child(div()).class("card"))
                .child(div())
                .child(crate::container_query(|size, window, cx| div()))
                .select(Select::this().reflects(crate::Styled), move |element| {
                    this_count.set(this_count.get() + 1);

                    element.bg(rgb(0x111111))
                })
                .select(Select::children().reflects(crate::Styled), move |element| {
                    children_count.set(children_count.get() + 1);

                    element.bg(rgb(0x222222))
                })
                .select(
                    Select::descendants().reflects(crate::Styled),
                    move |element| {
                        descendants_count.set(descendants_count.get() + 1);

                        element.bg(rgb(0x333333))
                    },
                )
                .select(
                    Select::children()
                        .reflects(crate::reflection::trait_set!(
                            crate::Styled,
                            crate::ParentElement
                        ))
                        .id("target")
                        .class("card"),
                    move |element| {
                        fn require_traits<ElementType>(element: &ElementType)
                        where
                            ElementType: Element + Styled + ParentElement,
                        {
                            std::hint::black_box(element);
                        }

                        require_traits(&element);
                        filtered_count.set(filtered_count.get() + 1);

                        element.bg(rgb(0x444444))
                    },
                )
        }
    }

    #[crate::test]
    #[allow(unused_variables)]
    fn selects_elements_by_scope_and_predicates(cx: &mut TestAppContext) {
        let this_count = Rc::new(Cell::new(0));
        let children_count = Rc::new(Cell::new(0));
        let descendants_count = Rc::new(Cell::new(0));
        let filtered_count = Rc::new(Cell::new(0));
        let window: AnyWindowHandle = cx
            .add_window({
                let this_count = this_count.clone();
                let children_count = children_count.clone();
                let descendants_count = descendants_count.clone();
                let filtered_count = filtered_count.clone();

                move |window, cx| SelectorView {
                    this_count,
                    children_count,
                    descendants_count,
                    filtered_count,
                }
            })
            .into();

        this_count.set(0);
        children_count.set(0);
        descendants_count.set(0);
        filtered_count.set(0);

        cx.update_window(window, |view, window, cx| {
            window.draw(cx).clear(cx);
        })
        .unwrap();

        assert_eq!(this_count.get(), 1);
        assert_eq!(children_count.get(), 2);
        assert_eq!(descendants_count.get(), 4);
        assert_eq!(filtered_count.get(), 1);
    }
}
